name: tadwer_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  sizer: ^2.0.15
  get_storage: ^2.1.1
  flutter_easyloading: ^3.0.5
  provider: ^6.0.5
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: DGAgnadeen
      fonts:
        - asset: assets/fonts/DGAgnadeen-Bold.ttf
        - asset: assets/fonts/DGAgnadeen-Extrabold.ttf
        - asset: assets/fonts/DGAgnadeen-Heavy.ttf
        - asset: assets/fonts/DGAgnadeen-Light.ttf
        - asset: assets/fonts/DGAgnadeen-Regular.ttf
        - asset: assets/fonts/DGAgnadeen-Thin.ttf
        - asset: assets/fonts/DGAgnadeen-Ultralight.ttf
